version: '3'
services: 
  db:
    image: mysql
    container_name: mysql
    ports: 
      - "3306:3306"
    env_file: .env 
    volumes: 
      - "mysql_volume:/var/lib/mysql"
volumes: 
  mysql_volume: